[package]
name = "tantivy"
version = "0.1.1"
authors = ["Paul Masurel <paul.masurel@gmail.com>"]
build = "build.rs"
license = "MIT"

description = """Tantivy is a search engine library."""

documentation = "http://fulmicoton.com/tantivy/tantivy/index.html"
homepage = "https://github.com/tantivy-search/tantivy"
repository = "https://github.com/tantivy-search/tantivy"

readme = "README.md"
keywords = ["search", "information", "retrieval"]

[dependencies]
byteorder = "0.4"
memmap = "0.2"
lazy_static = "0.1"
regex = "0.1"
#fst = "0.1"
fst = {path = "../fst"}
atomicwrites = "0.0.14"
tempfile = "2.0"
rustc-serialize = "0.3"
log = "0.3"
combine = "2.0.*"
tempdir = "0.3"
bincode = "0.4"
libc = {version = "0.2.6", optional=true}
num_cpus = "0.2"
itertools = "0.4"
lz4 = "1.13"
time = "0.1"
uuid = "0.1"
chan = "0.1"
crossbeam = "0.2"

[dev-dependencies]
rand = "0.3"

[build-dependencies]
gcc = {version = "0.3", optional=true}

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false


[features]
default = ["simdcompression"]
simdcompression = ["libc", "gcc"]
