[package]
name = "tantivy"
version = "0.2.0"
authors = ["Paul Masurel <paul.masurel@gmail.com>"]
build = "build.rs"
license = "MIT"
categories = ["database-implementations", "data-structures"]
description = """Tantivy is a search engine library."""
documentation = "https://tantivy-search.github.io/tantivy/tantivy/index.html"
homepage = "https://github.com/tantivy-search/tantivy"
repository = "https://github.com/tantivy-search/tantivy"
readme = "README.md"
keywords = ["search", "information", "retrieval"]

[dependencies]
byteorder = "1.0"
memmap = "0.4"
lazy_static = "0.2.1"
regex = "0.2"
fst = "0.1.37"
atomicwrites = "0.1.3"
tempfile = "2.1"
rustc-serialize = "0.3"
log = "0.3.6"
combine = "2.2"
tempdir = "0.3"
bincode = "0.5"
libc = {version = "0.2.20", optional=true}
num_cpus = "1.2"
itertools = "0.5.9"
lz4 = "1.20"
bit-set = "0.4.0"
time = "0.1"
uuid = { version = "0.4", features = ["v4", "rustc-serialize"] }
chan = "0.1"
version = "2"
crossbeam = "0.2"
futures = "0.1.9"
futures-cpupool = "0.1.2"

[target.'cfg(windows)'.dependencies]
winapi = "*"

[dev-dependencies]
rand = "0.3"
log4rs = "0.6"

[build-dependencies]
gcc = {version = "0.3", optional=true}

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false


[features]
default = ["simdcompression"]
simdcompression = ["libc", "gcc"]


[badges]
travis-ci = { repository = "tantivy-search/tantivy" }
